### ISSUE TITLE
Allow nested collections

### ISSUE THREAD

**Issue by jleehr** [a2lix/symfony-collection#10]
The current version does not allow nested collections.
There is a pull request for it from dop3: #8

**Comment by michael-full-stack** [comment]
yes and it's perfect

**Comment by webda2l** [comment]
Not convinced by the linked PR, but the entry.add.onAfterFn of the 0.5.1 offer enough flexibility to handle this case.

**Comment by cadot-eu** [comment]
ok, perfect ;-)
