### ISSUE TITLE
Add config option to specify custom template(s)

### ISSUE THREAD

**Issue by Amunak** [a2lix/symfony-collection#11]
We can set a button's label, but there's currently no way to set the content of a button (or any other template for that matter).

So if you want to add, say, an icon to the button's label, or an icon next to (or instead of) the collection's label, it's not possible.

More versatility would be useful.

**Comment by webda2l** [comment]
Hello, I close, give a try to the entry.add.prototype & entry.remove.prototype of the 0.5.1: see [Readme](https://github.com/a2lix/symfony-collection#how-to)
