### ISSUE TITLE
Allow HTML in buttons

### ISSUE THREAD

**Issue by garak** [a2lix/symfony-collection#14]
It would be nice if you could allow HTML in buttons.
Typically, I use to enhance my add/remove buttons with a small prepending icon (e.g. a "plus" icon for adding and a "trash" icon for removing).
This is currently not possible, I tried like so:
```
import a2lix_lib from "@a2lix/symfony-collection/src/a2lix_sf_collection";

a2lix_lib.sfCollection.init({
  collectionsSelector: "form div[data-prototype]",
  manageRemoveEntry: true,
  lang: {
    add: "<i class='fas fa-add'></i> add",
    remove: "<i class='fas fa-trash'></i> remove"
  }
})

```

but unfortunately the text is rendered as is

**Comment by webda2l** [comment]
Hello, I close, give a try to the entry.add.prototype & entry.remove.prototype of the 0.5.0: see [Readme](https://github.com/a2lix/symfony-collection#how-to)
