### ISSUE TITLE
Click on elements is prevented

### ISSUE THREAD

**Issue by garak** [a2lix/symfony-collection#19]
By inspecting my code, I see that this lib is adding a click event listener on the whole prototype div.
This prevents using anything inside the div itself that needs a click. For example, date fields cannot display the calendar, or bootstrap custom switches don't work.
I guess that the click event should listen to the click of the "add"/"remove" buttons instead

**Comment by garak** [comment]
I just tried to remove the custom bootstrap attribute from a checkbox, to try to mitigate this problem, but unfortunately it doesn't work either.

**Comment by garak** [comment]
@webda2l I know that it's not so nice to bump issues, but this one is already 3 weeks old, and it looks like a blocking one to me.
Could you take a look? Thanks

**Comment by webda2l** [comment]
Better to come back to stick to 0.4 version in your case. I don't know when I will fix this.

You can have a look to https://github.com/symfony/ux/pull/398 as alternative maybe.

**Comment by majermi4** [comment]
Hello, we have run into this same issue and it's also blocking us from using this library now. We depend on it quite a lot so we'd be very happy if it got fixed.

The fix should be very simple, basically switching the order of these operations: https://github.com/a2lix/symfony-collection/blob/master/src/a2lix_sf_collection.js#L115-L119

If the prevent default happened after the if check, everything should work as expected.

**Comment by majermi4** [comment]
I added a MR here which should fix the issue: https://github.com/a2lix/symfony-collection/pull/21

**Comment by webda2l** [comment]
Thanks @majermi4, sound right indeed. Release https://github.com/a2lix/symfony-collection/releases/tag/0.5.2
