### ISSUE TITLE
Configurations that do not specifiy entry.add or entry.remove are broken

### ISSUE THREAD

**Issue by sandermarechal** [a2lix/symfony-collection#22]
PR #15 broke configurations that do not specifiy entry.add or entry.remove explicitly. For example, the following is broken:

```
a2lix_lib.sfCollection.init({
    lang: {
      add: 'Custom add label',
      remove: 'Custom remove label'
    }
})
```

That is because any passed config must specifiy entry.add and entry.remove explicitly. If you do not, you will get the following error:

```
Uncaught TypeError: config.entry is undefined at a2lix_sf_collection:40:15
```

Instead, I now have to specifiy it as this:

```
a2lix_lib.sfCollection.init({
    entry: {
        add: {},
        remove: {},
    },
    lang: {
      add: 'Custom add label',
      remove: 'Custom remove label'
    }
})
```

I don't think that is how the default configuration should work.

**Comment by webda2l** [comment]
Fixed in https://github.com/a2lix/symfony-collection/releases/tag/0.6.0
