### ISSUE TITLE
keyword 'interface' is reserved

### ISSUE THREAD

**Issue by garak** [a2lix/symfony-collection#23]
After upgrading from 0.5.2 to 0.6.1:

>Uncaught Error: Module parse failed: The keyword 'interface' is reserved (3:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict'
| 
> interface ISfCollectionConfig {
|   collectionsSelector: string // Default: 'div[data-prototype]',
|   entry: {

**Comment by webda2l** [comment]
Previous README mentioned the use of the JS not minify version: `src/a2lix_sf_collection`, and it was a mistake. This JS not minify version is not provided anymore.
See https://github.com/a2lix/symfony-collection#basic-use and the fixed mention `dist/a2lix_sf_collection.min` to use.

**Comment by garak** [comment]
Thanks
