### ISSUE TITLE
Set item of Sub Form in a Customizing Table 

### ISSUE THREAD

**Issue by ShannonCodeur** [a2lix/symfony-collection#5]
Hello everyone, I'm really stuck and I need your help. Indeed, I use this bundle (a2lix/symfony-collection) and I manage to add and remove the elements following the demo. I would like to know if it is possible to customize the display of the form so that I can have a table where I would have more space on my page. Please. I'm not really doing well in jQuery. This is what i want
![form](https://user-images.githubusercontent.com/36988296/74556904-4e28b700-4f5f-11ea-9019-b258b9251244.JPG)

and this is what i have (Everithing is great
![homologation](https://user-images.githubusercontent.com/36988296/74556954-63054a80-4f5f-11ea-8093-c9455ffd90a3.JPG)
)

**Comment by webda2l** [comment]
Not the right place sorry, you need to upgrade your knowledge about Twig (https://symfony.com/doc/current/form/form_customization.html, https://twig.symfony.com/doc/3.x/templates.html) and CSS.
